### ISSUE TITLE
Add Sign In Page (GraphQL, Server Go, Nextjs)

### ISSUE THREAD

**Issue by sota0121** [sota0121/ec-sample#1]
## TODO

- [x] sign up 機能
- [ ] sign in 機能
- [ ] （あとでやる）バリデーションの実装 react-hook-form でサクッと
- [ ] (あとでやる)signin / signup page のコンポーネントを小さい単位に分ける
- [ ] 画面一覧の作成
- [ ] コンポーネント構成のざっくり設計

## Overview

Sign In page implementation.

現状はフロントしかないので、Sign InPageを作るということを目的に、諸々の枠組みを作る

- Frontend
  - Sign In 時にクッキーを設定する
  - ステートを導入する
- Server
  - GraphQL クエリを実装
  - gql-gen でコード生成
  - GraphQLのミューテーションをGoで実装
- Infra
  - User管理はFirebaseでやってみる（簡単そう＆安いから）
